### ISSUE TITLE
A read and pileup filtering DSL

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/pageant#6]
Not sure if this should go here or in Guacamole. If this gets implemented we'd definitely want to use it in Guacamole.

The plotting tools in `pageant` should take a specification of the read and pileup filters to apply. Instead of adding lots of arguments like `--min-mapping-quality X` we might consider defining a concise DSL that lets us specify these filters wherever they are needed, and support predicate logic, e.g. `(mapping_quality > 20) OR (mapping_quality > 10 && average_base_quality > 30)`.

Some example filters:

Read filters
- mapping quality
- is it a secondary alignment?
- average base quality
- is it a split read?
- number of bases mismatching the reference in this alignment

Pileup filters
- Number of reads aligning here and satisfying an arbitrary read filter
- Number of reads matching (or mismatching) reference
- Average base quality
- Strand bias

For a plot like what's described in https://github.com/hammerlab/pageant/issues/5 I'd like to be able to specify a filter like "pileups where at least 10 reads with mapping quality > 20 are mapped"

GATK has a thing for specifying arbitrary read filters but it's not very flexible: http://gatkforums.broadinstitute.org/discussion/2338/how-can-i-pass-read-filters-and-their-arguments-at-the-command-line

**Comment by hammer** [comment]
Seems like a fit for SparkSQL?

**Comment by ryan-williams** [comment]
Closing this for now; SparkSQL or some impala- or kudu-based tool would probably be better suited to this than the kinds of things that are currently here.
