### ISSUE TITLE
Compute regression-line coefficients for joint-read-depth-histogram

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/pageant#7]

**Comment by timodonnell** [comment]
My thought would be to focus `pageant` only on spark analyses that take BAMs and write out something like a csv file with the results, and avoid dealing with the inevitable huge long tail of plots people will want to generate from this data. 

My most common scenario for looking at plots is when I'm already running ipython notebook, where I can easily generate the plot myself (and subsequent analyses like regression lines). It's pretty rare in my experience to want to just generate a pdf plot with a script without wanting to manipulate the data and the plot myself in python in some way. 

For nontrivial plotting tasks that we want to make reusable, the "genomisc" module I put up might be one place to put it: https://github.com/timodonnell/genomisc . But for things like scatter plots with regression lines, unless we're doing something clever, I'm not sure it necessitates a library function.

**Comment by ryan-williams** [comment]
That makes sense. I think there's some experimenting that's worth doing re: where to draw the line between Spark and matplotlib, and for a few simple things like this we can probably try both while we develop a feel for it.

Computing the two parameters of the regression line is a one/two-liner in Spark (I did a close relative of that calculation in a `spark-shell` yesterday in a couple of seconds on the millions of data points in the two samples I'm currently comparing); if there's an easy way to throw **that** result over the wall to matplotlib, and have one less pass over millions of data on my laptop, that might make more sense. I don't know enough matplotlib to know whether that is possible / how amenable it might be to allowing us to plug variously-precomputed aspects of our plots in to it, so that's something I need to investigate / would love to hear thoughts on. I am not trying to write my own plotting code, just tell matplotlib a slope+intercept rather than have it arduously/inefficiently recompute numbers I already know.

My current thinking on an ideal to move toward is a notebook setup where we can write Scala/Python-Spark commands and consume/plot the results in non-spark Python. IIUC the spirit of your concern is that we shouldn't waste effort duplicating plot logic, and I definitely agree with that, I just also think we should not blow up our iteration times by having matplotlib do O(n) passes over the data on our laptops more than we have to (that is where my initial work on pageant stalled out), and I want to explore the space between those two constraints a little bit.

Let me know what you think!

**Comment by timodonnell** [comment]
Gotcha, thanks. I agree that agree that if matplotlib is the slow step something is going wrong, and we'll need to experiment to find the right specification for each analysis so the output has the data we need while still being easily analyzed interactively.

For the specific case of the read depth histogram, probably the csv output should be binned counts (it's a histogram, after all). So for a 2d histogram with a bin width of 10 and max bin 1000, we would have a count for how many loci have e.g. sample1_depth between [0,10) and sample2_depth between [30, 40), and so on for all pairs of bins 0-10, 10-20, 20-30, ... 990-1000 (might want to have a bin for >1000 too). That would give us (1000/10)^2 = 10,000 counts, which would be a very manageable dataset to analyze interactively in ipython, including computing a best fit line.

The idea to do interactive analyses in Spark sounds interesting. On one hand it feels really strange to have the whole cluster allocated and waiting on me to type keys (is that how it works?), but if we can get that kind of thing sorted out, sounds like could be a much more flexible environment.

**Comment by ryan-williams** [comment]
- agreed that binning/downsampling will likely be two key pillars of whatever gross+emergent CSV-serde-or-equivalent API develops here between Spark and matplotlib.
- IIRC from running the #'s yesterday, these 2 BAMs' joint-hist was about 20,000 x 20,000 with 3.5MM non-zero locations, every square in [0,1000) x [0,1000), and presumably further out, was non-zero.
  - restricting to exons / capture-targeted areas (per #2) will likely help this a lot, though comparing these shapes for {all, exons, non-exons} would also be interesting and is something I'd like to do.
  - It's not obvious to me what the bin sizes should be; at the very least log-scaled bins seem like they'd make more sense than fixed-width. In the limit I can imagine some other variable-sized binning that might further tease out some structure to the data, so there's some questions I'd like to answer there, presumably involving analysis more in Spark than in matplotlib. Again, I definitely agree that this is stuff that pageant should do in Spark-land before feeding a plot-data-model to MPL.
- re: interactive spark analyses, that's what I've been doing with Spark shells, and it's true that hogging many resources for it can be clumsy. However:
  - if I only do it when I'm actually running analyses (and don't leave them sitting around idle, which I have done), then I don't think it's much/any worse than `spark-submit`ing the equivalent job; for pageant today I mostly run one command in my `spark-shell` that runs ~20 jobs to compute the thing I then want to interactively analyze.
  - More importantly, Spark has dynamic executor allocation which should make this all free/ideal. I'm going to try to get that working today and will lyk how it goes.

**Comment by timodonnell** [comment]
Cool, interested how the dynamic executor stuff goes.

I'd stick with fixed sized bins plus an overflow bin (with the bin width and number of bins an arguments of course). Restricting to exon capture will be very useful too.
